### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by gui-yuzhi** [YimianDai/sirst#3]
你好，我下载之后，数据集的压缩包显示有错误，请问是什么原因，可以下载这个数据集吗？

**Comment by YimianDai** [comment]
这个数据集被很多人下载过了，没有听到有反应您所说的问题的。

如果您下载 zip 有问题，那就采用 git clone。

**Comment by gui-yuzhi** [comment]
作者你好，可以邮件发一份吗？感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YimianDai/sirst"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月26日(星期天) 晚上9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YimianDai/sirst] 数据集 (#3)





 
这个数据集被很多人下载过了，没有听到有反应您所说的问题的。
 
如果您下载 zip 有问题，那就采用 git clone。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 2755296893** [comment]
你好，为什么我下载的数据集里sirst-master\sirst-master\images\__MACOSX\images里面的png图片打不开，而且图片都是1KB,这是下载错误还是正常的

**Comment by YimianDai** [comment]
MACOSX 是 mac os 系统自动生成的隐藏文件夹，图像并不在这个里面。

2755296893 ***@***.***> 于2021年10月19日周二 上午10:09写道：
