### ISSUE TITLE
戴博士您好，关于数据集我想请教一个问题。在此数据集中包含多个目标的情况，可为什么在xml标注文件中只有一个标注框呢？

### ISSUE THREAD

**Issue by grenoble-zhang** [YimianDai/sirst#5]
戴博士您好，关于数据集我想请教一个问题。在此数据集中包含多个目标的情况，可为什么在xml标注文件中只有一个标注框呢？

**Comment by Sunyx93** [comment]
戴博士，您好，和GuiYu-wq遇到了同样的问题，发现针对有多个目标的情况下，在xml文件仅有一个标注框，同时，标注位置也是错误的。

**Comment by QYR123** [comment]
戴博士你好，我也遇到了在有多个目标的时候标注框只有一个，看了一下这个标注框是把两个目标一起框起来的，这样子影响了训练，希望您能看一下，就比如第1张图片

**Comment by YimianDai** [comment]
https://github.com/YimianDai/open-sirst-v2

用 V2 的数据吧

**Comment by YimianDai** [comment]
> 戴博士，您好，和 GuiYu-wq 遇到了同样的问题，发现针对有多个目标的情况下，在 xml 文件仅有一个标注框，同时，标注位置也是错误的。

我今天反应过来了，您应该是把 RectLabel 语义分割可视化的 XML 当成 BBox 的 XML 了，才有这个问题。

**Comment by YimianDai** [comment]
> 戴博士你好，我也遇到了在有多个目标的时候标注框只有一个，看了一下这个标注框是把两个目标一起框起来的，这样子影响了训练，希望您能看一下，就比如第 1 张图片

您应该是把 RectLabel 语义分割可视化的 XML 当成 BBox 的 XML 了，才有这个问题，直接用 V2 的数据吧 https://github.com/YimianDai/open-sirst-v2
